# FROM openjdk:17-jdk-alpine
FROM openjdk:17-oracle
ARG JAR_FILE=./wakepercent/build/libs/*.jar
COPY ${JAR_FILE} app.jar

RUN apt-get update -y && apt-get install -y mysql-community-client
# ENTRYPOINT ["java","-jar","/app.jar"]