spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/hotel
    username: root
    password: My$ql000
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create # 로딩 시점에 테이블을 다 Drop 후 다시 생
    properties:
      hibernate:
        # show_sql: true # JPA가 실행하는 Query를 콘솔에 출력 > logging.level로 대체(콘솔 출력이 아닌 로그 파일로 생성)
        format_sql: true # Query가 한줄로 나오는게 아니라 Format 형식에 맞춰서 출
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace